[project]
name = "twain-wifco"
version = "0.0.1"
description = "TWAIN WInd Farm Control Optimization"
authors = [
  { name = "Bart Wolleswinkel", email = "b.wolleswinkel@tudelft.nl"},
  { name = "Wolfram Martens", email = "w.martens@tudelft.nl" }
]

readme = "README.md"

dependencies = [
]

[tool.pytest.ini_options]
testpaths = ["tests"]
